version: "3"
services:
  db:
    image: mysql:8.0.29
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3306:3306
    tty: true
  api:
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile_prd
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
      - ./backend/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db
  front:
    env_file:
      - ./frontend/react-app/.env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - ./frontend/.env
    command: sh -c "yarn start"
    # command: sh -c "npm run build && npm install -g serve && serve -s build"
    ports:
      - "3000:3000"
  terraform:
    image: hashicorp/terraform:1.2.3
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
volumes:
  mysql-data: