name: "Terraform"

on:
  push:

env:
  OIDC_ARN: ${{ secrets.AWS_OIDC_ARN }}
  TF_VAR_tool: "terraform"
  TF_VAR_project: "tf-rails-fargate"
  TF_VAR_environment: "production"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
